import { Component, OnInit } from '@angular/core';
import { NonNullableFormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { LearningService } from '@services/learning.service';

@Component({
  selector: 'create-learning',
  templateUrl: './create-learning.component.html',
})
export class CreateLearningComponent implements OnInit {
  classId!: number;

  learningInsertReqDto = this.fb.group({
    learningName: ['', Validators.required],
    learningCode: ['', Validators.required],
    forumName: ['Forum Generated By System', Validators.required],
    classId: [0, Validators.required],
    startTime: ['', Validators.required],
    endTime: ['', Validators.required],
  });

  constructor(
    private fb: NonNullableFormBuilder,
    private router: Router,
    private activatedRoute: ActivatedRoute,
    private learningService: LearningService
  ) {}

  ngOnInit(): void {
    this.activatedRoute.paramMap.subscribe((params) => {
      this.classId = Number(params.get('id'));
      this.learningInsertReqDto = this.fb.group({
        learningName: ['', Validators.required],
        learningCode: ['', Validators.required],
        forumName: ['Forum Generated By System', Validators.required],
        classId: [Number(params.get('id')), Validators.required],
        startTime: ['', Validators.required],
        endTime: ['', Validators.required],
      });
    });
  }

  onCreate() {
    const data = this.learningInsertReqDto.getRawValue();
    this.learningService.insert(data).subscribe((res) => {
      this.router.navigateByUrl(`learning/${this.classId}`);
    });
  }
}
